services:
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    restart: unless-stopped

volumes:
  media_volume:
  static_volume: