# Generated by Django 5.2.10 on 2026-02-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_person_account_status_person_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='generation_char',
            field=models.CharField(blank=True, max_length=10, verbose_name='辈份字'),
        ),
    ]
