# Generated by Django 5.2.10 on 2026-02-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_person_is_outsider_spouserelation_relation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generation',
            options={'ordering': ['number', 'is_spouse'], 'verbose_name': '世代', 'verbose_name_plural': '世代'},
        ),
        migrations.AddField(
            model_name='generation',
            name='is_spouse',
            field=models.BooleanField(default=False, verbose_name='是否为配偶世代'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='number',
            field=models.IntegerField(verbose_name='世代数'),
        ),
        migrations.AlterUniqueTogether(
            name='generation',
            unique_together={('number', 'is_spouse')},
        ),
    ]
