# Generated by Django 5.2.10 on 2026-02-02 05:34

import genealogy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0007_genealogyrecord_source_image_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genealogyrecord',
            name='source_image',
            field=models.ImageField(blank=True, null=True, upload_to='record_images/', validators=[genealogy.models.validate_image_extension, genealogy.models.validate_file_size], verbose_name='来源图片'),
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[genealogy.models.validate_image_extension, genealogy.models.validate_file_size], verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='image',
            field=models.ImageField(upload_to='person_images/', validators=[genealogy.models.validate_image_extension, genealogy.models.validate_file_size], verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='personvideo',
            name='video',
            field=models.FileField(upload_to='person_videos/', validators=[genealogy.models.validate_video_extension, genealogy.models.validate_video_size], verbose_name='视频'),
        ),
    ]
