# Generated by Django 5.2.11 on 2026-02-12 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0009_remove_generation_generation_char_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('total_visits', models.IntegerField(default=0, verbose_name='总访问量')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='独立访客数')),
                ('unique_ips', models.IntegerField(default=0, verbose_name='独立IP数')),
            ],
            options={
                'verbose_name': '每日访问统计',
                'verbose_name_plural': '每日访问统计',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageVisitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True, verbose_name='页面路径')),
                ('total_visits', models.IntegerField(default=0, verbose_name='总访问量')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='独立访客数')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '页面访问统计',
                'verbose_name_plural': '页面访问统计',
                'ordering': ['-total_visits'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='访问URL')),
                ('path', models.CharField(max_length=500, verbose_name='访问路径')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='来源页面')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='会话密钥')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('is_unique_visit', models.BooleanField(default=False, verbose_name='是否独立访问')),
                ('visit_date', models.DateField(verbose_name='访问日期')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='访问用户')),
            ],
            options={
                'verbose_name': '页面访问记录',
                'verbose_name_plural': '页面访问记录',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='genealogy_p_timesta_f5fcdd_idx'), models.Index(fields=['path', 'visit_date'], name='genealogy_p_path_46efc1_idx'), models.Index(fields=['ip_address', 'visit_date'], name='genealogy_p_ip_addr_86ae4b_idx')],
            },
        ),
    ]
