# Generated by Django 6.0.1 on 2026-02-01 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='支系名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='分布地区')),
            ],
            options={
                'verbose_name': '支系',
                'verbose_name_plural': '支系',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='世代数')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='世代名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '世代',
                'verbose_name_plural': '世代',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('courtesy_name', models.CharField(blank=True, max_length=100, verbose_name='字')),
                ('art_name', models.CharField(blank=True, max_length=100, verbose_name='号')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='别名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='出生年份')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='逝世年份')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='出生地')),
                ('burial_place', models.CharField(blank=True, max_length=300, verbose_name='葬地')),
                ('burial_fengshui', models.CharField(blank=True, max_length=200, verbose_name='墓形/风水')),
                ('burial_direction', models.CharField(blank=True, max_length=100, verbose_name='坐向')),
                ('biography', models.TextField(blank=True, verbose_name='生平简介')),
                ('achievements', models.TextField(blank=True, verbose_name='主要事迹')),
                ('descendants_location', models.TextField(blank=True, verbose_name='后裔分布')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='genealogy.branch', verbose_name='所属支系')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='genealogy.person', verbose_name='父亲')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='genealogy.generation', verbose_name='世代')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='genealogy.person', verbose_name='母亲')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
                'ordering': ['generation__number', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GenealogyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='来源')),
                ('page_number', models.CharField(blank=True, max_length=50, verbose_name='页码')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('related_persons', models.ManyToManyField(blank=True, related_name='records', to='genealogy.person', verbose_name='相关人物')),
            ],
            options={
                'verbose_name': '族谱记录',
                'verbose_name_plural': '族谱记录',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_branch', to='genealogy.person', verbose_name='开基祖'),
        ),
        migrations.CreateModel(
            name='SpouseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='排序（第几任）')),
                ('husband', models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='husband_relations', to='genealogy.person', verbose_name='丈夫')),
                ('wife', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='wife_relations', to='genealogy.person', verbose_name='妻子')),
            ],
            options={
                'verbose_name': '配偶关系',
                'verbose_name_plural': '配偶关系',
                'ordering': ['husband', 'order'],
                'unique_together': {('husband', 'wife')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='partners', through='genealogy.SpouseRelation', to='genealogy.person', verbose_name='配偶'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_users', to='genealogy.person', verbose_name='关联族谱人物')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
