# Generated by Django 5.2.10 on 2026-02-01 12:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_status',
            field=models.CharField(choices=[('active', '激活'), ('inactive', '未激活'), ('disabled', '禁用')], default='inactive', max_length=20, verbose_name='账号状态'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='person',
            name='related_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_person', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='person_images/', verbose_name='图片')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='genealogy.person', verbose_name='人物')),
            ],
            options={
                'verbose_name': '人物图片',
                'verbose_name_plural': '人物图片',
            },
        ),
        migrations.CreateModel(
            name='PersonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='person_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'wmv', 'flv'])], verbose_name='视频')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='genealogy.person', verbose_name='人物')),
            ],
            options={
                'verbose_name': '人物视频',
                'verbose_name_plural': '人物视频',
            },
        ),
    ]
