# Generated by Django 5.2.10 on 2026-02-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_generation_generation_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_outsider',
            field=models.BooleanField(default=False, verbose_name='是否为外族配偶'),
        ),
        migrations.AddField(
            model_name='spouserelation',
            name='relation_type',
            field=models.CharField(choices=[('marriage', '婚姻'), ('concubine', '妾室'), ('adopted', '继配')], default='marriage', max_length=20, verbose_name='关系类型'),
        ),
        migrations.AddField(
            model_name='spouserelation',
            name='source_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='配偶来源信息（如：某村某氏）'),
        ),
        migrations.AlterField(
            model_name='person',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='genealogy.generation', verbose_name='世代'),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='partners', through='genealogy.SpouseRelation', through_fields=('husband', 'wife'), to='genealogy.person', verbose_name='配偶'),
        ),
    ]
