# Generated by Django 5.2.10 on 2026-02-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0005_alter_generation_options_generation_is_spouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouserelation',
            name='relation_type',
            field=models.CharField(choices=[('marriage', '婚姻'), ('concubine', '妾室'), ('adopted', '继配'), ('zhuazhui', '招赘')], default='marriage', max_length=20, verbose_name='关系类型'),
        ),
    ]
