# Generated by Django 5.2.10 on 2026-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0006_alter_spouserelation_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genealogyrecord',
            name='source_image',
            field=models.ImageField(blank=True, null=True, upload_to='record_images/', verbose_name='来源图片'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', help_text='性别变动后需要先保存，然后重新加载页面以更新配偶关系选项', max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_outsider',
            field=models.BooleanField(default=False, help_text='外族配偶状态变动后，世代选项会自动更新；若需更新配偶关系选项，请保存并重新加载页面', verbose_name='是否为外族配偶'),
        ),
    ]
