# Generated by Django 5.2.10 on 2026-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0008_alter_genealogyrecord_source_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='generation_char',
        ),
        migrations.AddField(
            model_name='person',
            name='generation_char',
            field=models.CharField(blank=True, max_length=10, verbose_name='辈份字'),
        ),
    ]
