# Generated by Django 5.2.11 on 2026-02-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0010_dailyvisitstats_pagevisitstats_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouserelation',
            name='relation_type',
            field=models.CharField(choices=[('marriage', '婚姻'), ('concubine', '妾室'), ('adopted', '继配'), ('zhuazhui', '招赘'), ('first', '一房'), ('second', '二房'), ('third', '三房'), ('fourth', '四房'), ('fifth', '五房')], default='marriage', max_length=20, verbose_name='关系类型'),
        ),
    ]
